services:
  webserver:
    image: cosmopolitan-webserver
    container_name: cosmopolitan-webserver
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - .env.prod
    environment:
      TZ: Europe/Berlin
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"

  worker:
    image: cosmopolitan-worker
    container_name: cosmopolitan-worker
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    env_file:
      - env_prod
    environment:
      TZ: Europe/Berlin
# Environment variables managed by system administration
# EMAIL_PASSWORD
# POSTGRES_PASSWORD
# OBJECT_STORAGE_REMOTE_NAME
# OBJECT_STORAGE_SECRET_KEY
