version: "3.8"

services:
  cosmopolitan-local:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - GIT_PAT_SM=${GIT_PAT_SM}
        - SM_BRANCH=${SM_BRANCH}
    env_file: .env
    image: cosmopolitan-local
    container_name: cosmopolitan-local
    volumes:
      - "./cosmopolitan_app:/python_docker/cosmopolitan/cosmopolitan_app"
    ports:
      - "${PORT}:${PORT}"
