# Docker Compose override for local soil-moisture-prediction development
# Usage: docker compose -f docker-compose.yml -f docker-compose.local_smp.yml up
# To set other smp path use: export SOIL_MOISTURE_PREDICTION_PATH="/foo/bar"

services:
  webserver:
    volumes:
      - "${SOIL_MOISTURE_PREDICTION_PATH:-/home/andersj/git/soil-moisture-prediction}:/python_docker/soil-moisture-prediction"
    environment:
      - PYTHONPATH=/python_docker/cosmopolitan:/python_docker/soil-moisture-prediction

  worker:
    volumes:
      - "${SOIL_MOISTURE_PREDICTION_PATH:-/home/andersj/git/soil-moisture-prediction}:/python_docker/soil-moisture-prediction"
    environment:
      - PYTHONPATH=/python_docker/cosmopolitan:/python_docker/soil-moisture-prediction
