[tool.poetry]
name = "cosmopolitan"
version = "0.0.43"
description = "COSmic ray based soil MOisture PredictiOn LIve descicion Tree ANalysis"
authors = ["John Anders <john-eric.anders@ufz.de>"]
readme = "README.md"
packages = [
    { include = "cosmopolitan_app" }
]

[tool.poetry.dependencies]
python = "^3.11"
selenium = ">=4.0.0"
dash = {extras = ["testing"], version = "^3.0.4"}
soil-moisture-prediction = "^0.0.42"
dash-bootstrap-components = "^2.0.3"
apscheduler = "^3.11.0"
dotenv = "^0.9.9"
psycopg2 = "^2.9.10"
sqlalchemy = "^2.0.41"
geoalchemy2 = "^0.17.1"
shapely = "^2.1.1"
pycairo = "^1.28.0"
py-staticmaps = "^0.4.0"
coolname = "^2.2.0"
pyproj = "^3.7.1"
email-validator = "^2.2.0"
gunicorn = "^23.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
