apiVersion: v2
name: cosmopolitan
description: A Helm chart for COSMic ray based sOil MOisture PredictiOn LIve descicion Tree ANalysis.
type: application
version: "0.4.0-alpha1"
appVersion: "latest"

maintainers:
  - name: "Hannes Bohring"
    email: "hannes.bohring@ufz.de"

home: "https://cosmopolitan.web.app.ufz.de/"
sources:
  - "https://codebase.helmholtz.cloud/ufz/tb5-smm/met/wg7/cosmopolitan"

icon: "https://cosmopolitan.web.app.ufz.de/static/favicon.ico"

annotations:
  rdm.ufz.de/inception-date: "20240220"
  rdm.ufz.de/duration-in-years: "2"

dependencies:
  - name: frontend
    version: "0.1.0"
  - name: worker
    version: "0.1.0"
  - name: tileserver
    version: "0.1.0"
