persistence:
  enabled: false
  storageClassName: ""
  name: "cosmopolitan-work-dir-pvc"
  size: "10G"

frontend:
  enabled: true
  image:
    repository: registry.hzdr.de/ufz/tb5-smm/met/wg7/cosmopolitan
    tag: "latest"

  imagePullSecrets: []

  environmentVariables:
    - name: "EMAIL_PORT"
      value: "587"
    - name: "EMAIL_SENDER"
      value: "cosmopolitan@example.de"
    - name: "EMAIL_SERVER"
      value: "smtp.example.de"
    - name: "EMAIL_USERNAME"
      value: "user_name"
    - name: "EMAIL_PASSWORD"
      value: ""
    - name: "FLASK_DEBUG"
      value: "0"
    - name: "FLASK_PORT"
      value: "8080"
    - name: "MAINTAINER_EMAIL"
      value: ""
    - name: "OBJECT_STORAGE_BUCKET"
      value: "cosmopolitan-prod"
    - name: "OBJECT_STORAGE_HOST"
      value: "https://s3"
    - name: "OBJECT_STORAGE_REMOTE_NAME"
      value: "cosmopolitan-remote"
    - name: "OBJECT_STORAGE_ACCESS_KEY"
      value: ""
    - name: "OBJECT_STORAGE_SECRET_KEY"
      value: ""
    - name: "POSTGRES_DB"
      value: "somweb_prod"
    - name: "POSTGRES_HOST_NAME"
      value: "postgres.intranet.ufz.de"
    - name: "POSTGRES_PORT"
      value: "5432"
    - name: "POSTGRES_USER"
      value: "somweb_prod_rw"
    - name: "POSTGRES_PASSWORD"
      value: ""
    - name: "CLUSTER_TOKEN"
      value: ""
    - name: "WEB_OUTSIDE_URL"
      value: "https://cosmopolitan.example.de"
    - name: "WEB_WORK_DIR"
      value: "./cosmopolitan_app/work_dir"

  ingress:
    enabled: false
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        add_header 'X-Content-Type-Options' 'nosniff' always;
        add_header 'Content-Security-Policy' "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' ; frame-src 'self'; child-src 'self' ; object-src 'none' ; frame-ancestors 'self';" always;
        add_header 'X-XSS-Protection' '1';
    hosts:
      - host: "cosmopolitan.example.com"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: cosmopolitan-example-com
        hosts:
          - "cosmopolitan.example.com"

  resources: {}

worker:
  enabled: true

  image:
    repository: registry.hzdr.de/ufz/tb5-smm/met/wg7/cosmopolitan
    tag: ""

  imagePullSecrets: []
#    - name: "wombat-docker-registry-codebase"

  resources: {}

tileserver:
  enabled: true
